os: linux
language: node_js
node_js:
  - lts/*

cache:
 npm: true
 directories:
  - node_modules
  - ~/.cache

branches:
 only:
  - master

install:
 - npm install

script:
 - npm run build

before_deploy:
 - mkdir -p public
 - mv dist/index.html public
 - mv dist/main.min.js public
 - mv dist public

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  webhooks: https://www.travisbuddy.com
