dist: xenial
os: linux
language: generic

cache:
  directories:
    - ./admin/node_modules/
    - ~/.cache

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh # this is for api deploy

script:
  - bash deploy.api.sh
  - bash build.admin.sh

branches:
  only:
    - master
    - dev/api

deploy: # spurb.github.io/piu-monitoramento
  local_dir: admin/gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  webhooks: https://www.travisbuddy.com