language: node_js
node_js:
  - lts/*

cache:
  directories:
    - ./admin/node_modules/
    - ~/.cache

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh # this is for api deploy

script:
  - bash deploy.api.sh

branches:
  only:
    - master
    - dev/api